### ISSUE TITLE
Object has no attribute 'RenderToSVG'

### ISSUE THREAD

**Issue by fernandomoraangel** [rism-ch/verovio#1212]
I'm working in Windows with Python 3.7. All seems ok and when I try to render SVG, I get a message "object has no attribute 'RenderToSVG'". I read in toolkit.h and the atribute exists. What can I do?

![Screen capture](https://user-images.githubusercontent.com/11945850/70109612-6c4a7080-161a-11ea-8f24-3fd1689a3e29.PNG)

**Comment by lpugin** [comment]
Python methods are camelCase. Which means you need to call `renderToSVG` and not `RenderToSVG`
